### ISSUE TITLE
Directory can't be created

### ISSUE THREAD

**Issue by lupomeo** [EuFlo/sacd-ripper#4]
Directory can't be created

**Comment by EuFlo** [comment]
I can confirm the problem. 
When running in Windows cmd prompt and the output (-o) folder is not specified, the folder can't be created.
That is because in Windows we uses absolute paths.

As a rapid workaround: set the option -o to 'desired directory'
 Example:
 sacd_extract -s -i input.iso -o c:\outputfolder

Fixed in next version: 0.3.9.3-89
